title: "Name"
description: "Research group homepage."
author: "Author"

baseurl: "/website"
url: "https://arthys86.github.io"

# Theme
#remote_theme: daattali/beautiful-jekyll@6.0.1

#plugins:
#  - jekyll-remote-theme

site-css:
  - "/assets/css/custom-styles.css"

navbar-links:
  Home: ""
  Members: "members"
  Publications: "publications"
  Research: "research"
  #Join: "join"
  #Contact: "contact"

# footer links
social-network-links:
  email: "12332386@mail.sustech.edu.cn"
  #github: "Arthys86"
