title: "Your Lab Name"
description: "Research group homepage."
author: "Your Lab"

baseurl: "/website"
url: "https://arthys86.github.io"

# Theme
remote_theme: daattali/beautiful-jekyll@6.0.1

plugins:
  - jekyll-remote-theme

site-css:
  - "/assets/css/custom-styles.css"

navbar-links:
  Home: ""
  People: "people"
  Publications: "publications"
  Research: "research"
  #Join: "join"
  #Contact: "contact"

# footer links
social-network-links:
  email: "12332386@mail.sustech.edu.cn"
  github: "Arthys86"
