title: "Name"
description: "default subtitle"
author: "Author"

baseurl: "/website"
url: "https://arthys86.github.io"

site-css:
  - "/assets/css/custom-styles.css"

navbar-links:
  Home: ""
  Members: "members"
  Publications: "publications"
  Research: "research"
  #Join: "join"
  #Contact: "contact"

# footer links
social-network-links:
  email: "12332386@mail.sustech.edu.cn"
  github: "Arthys86"
